### ISSUE TITLE
.scrollIntoViewIfNeeded()

### ISSUE THREAD

**Issue by epitaphmike** [iamdustan/smoothscroll#31]
Any chance you plan on adding support for Element.scrollIntoViewIfNeeded()?

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded

**Comment by jeremenichelli** [comment]
It's not right now, basically because it's not an official standard and has only been implemented in WebKit, but if it makes the cut some day we'll have to :)

**Comment by yukulele** [comment]
Scroll into view now have a descent support https://caniuse.com/#feat=scrollintoviewifneeded and should not be really hard to implement from current polyfill

**Comment by iamdustan** [comment]
@yukulele `Element.scrollIntoViewIfNeeded` is not on an official standards track nor will it be.

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded
https://www.w3.org/Bugs/Public/show_bug.cgi?id=17152

`scrollIntoView({ behavior: 'smooth', block: 'center' });` is the spec’d way to achieve that effect.

**Comment by jeremenichelli** [comment]
As @iamdustan said, this is a WebKit only thing, not an official spec.

**Comment by alejandroiglesias** [comment]
@iamdustan I guess you mean `scrollIntoView({ behavior: 'smooth', block: 'nearest' });` (notice `block: 'nearest'`) is the spec'd way to acheive `scrollIntoViewIfNeeded`?

**Comment by jeremyburton** [comment]
As Safari and Safari on iOS don't support the options parameter of scrollIntoView(), the only way I have found that I can align an element to the *bottom* of the scroll container is to use scrollIntoViewIfNeeded. Unfortunately, this proprietary WebKit method isn't supported by this polyfill so I can't have both bottom alignment and smooth scrolling. Unless someone knows better!? Otherwise, I either have to hope this polyfill is updated to support scrollIntoViewIfNeeded or WebKit adds support for the aforementioned options parameter. My app is targeted at mobile Safari so I'm really keen to find a solution :)
