### ISSUE TITLE
Position calculating bug on Chrome

### ISSUE THREAD

**Issue by KitaitiMakoto** [iamdustan/smoothscroll#36]
@iamdustan 
Hi,

Thank you for useful library. It helps me very well.

But I found a case Chrome doesn't work fine. A picture is worth a thousand words, you can see that at here:
https://kitaitimakoto.github.io/smoothscroll/#nesting

Links to "Nesting child 0X" don't lead you to target section but the top of "Nesting" section when using Chrome. Firefox and Safari work fine. 
Do you have any idea about this behavior and fixing it?

My example's source code is here:
https://github.com/iamdustan/smoothscroll/compare/master...KitaitiMakoto:nesting?expand=1

Thanks.

**Comment by jeremenichelli** [comment]
This is one of the edge cases where the scripts has a hard time trying to find if the element you want to scroll into view is inside a scrollable element or is the body itself.

By looking at the code the _#nesting-parent_ has a `position: absolute` and the _nesting childs_ `overflow: scroll` which in Chrome might cause a difference between the height and the scrollHeight property of the parent, which makes the script think that _#nesting-parent_ is a scrollable element.

If you remove the `position: absolute` from _#nesting-parent_ the script will work well. Since this is not a real case scenario it's hard to find where the script is failing exactly.

We are aware that this is probably the weakest part of the polyfill, but it's hard to infere how a fix could solve this situation since the example is a little messy.

Thanks for reporting.

**Comment by KitaitiMakoto** [comment]
Yes, if I remove `position: absolute`, Chrome works fine.
But it is required in my real use case(sorry, I cannot publish it for now). So, I'm using this library with patch.

I realize it's hard to dig deeper and fix it so I'm not intended to hurry you. I raised this issue just for your information. How about to write about this issue in README till it's fixed?

**Comment by jeremenichelli** [comment]
Sounds good, but I feel that more insight is needed to be more accurate on what is exactly what the script is missing.

For now, let's leave this issue _open_ since it's the purpose of the issues tab indeed. But please, let me know when your project is live to debug more deeply and be able to determinate the problem with better precision.

**Comment by KitaitiMakoto** [comment]
> For now, let's leave this issue open since it's the purpose of the issues tab indeed.

Okay.

> But please, let me know when your project is live to debug more deeply and be able to determinate the problem with better precision.

Of course okay although actually I'm patching this lib in my project. And more notice on this issue board will be required at that time because the site is written in Japanese. Its HTML structure and CSS might help you to research.

I respect your effort to solve problems. Thank you very much!

**Comment by jeremenichelli** [comment]
No problem @KitaitiMakoto, keep us in the loop so we can investigate further.

**Comment by KitaitiMakoto** [comment]
Hi,
Our site was published:
https://lp.koyamachuya.com/uchurinchu/

It uses smoothscroll lib with patch. The patch is hosted on my `nonesting` branch:
https://github.com/KitaitiMakoto/smoothscroll/tree/nonesting

Here is site description:
At first, when assets are loaded, a button to continue appears.
![](https://gyazo.com/971e1f5b20e534a071c028e46a6d8ff7.png)
After click the button(it uses your smoothscroll but patch is not required here),

**Comment by KitaitiMakoto** [comment]
(Sorry, I pushed comment button by mistake. will continue description...)

After you click the button(it uses your smoothscroll but patch is not required here), some contents and four pink dots on the left appear.
![](https://gyazo.com/bc751ba808820a4ce7651b006f1ebd91.png)
This smoothscroll lib is used for the dots with patch. If the patch is not applied, they don't work well on Chrome.

Is this description enough? Because I know my English is not good, please feel free to ask questions to clear things. Thanks!

**Comment by jeremenichelli** [comment]
Hi @KitaitiMakoto, the explanation is more than clear.

Sorry to ask for one more thing, but can you summit a pull request with the exact change you needed to do to get it working?

**Comment by KitaitiMakoto** [comment]
@jeremenichelli 
OK, done here: https://github.com/iamdustan/smoothscroll/pull/40

**Comment by jeremenichelli** [comment]
Excellent, thanks @KitaitiMakoto. As soon as I have time I'll try to replicate the bug and see If I can come with a solution to it.

**Comment by KitaitiMakoto** [comment]
Thank you!

**Comment by jeremenichelli** [comment]
This issue should be solved now that https://github.com/iamdustan/smoothscroll/pull/41 was merged. Closing.

**Comment by KitaitiMakoto** [comment]
I confirmed this fixed, great! Thank you, @jeremenichelli !

**Comment by jeremenichelli** [comment]
Thanks you for reporting and helping find the issue @KitaitiMakoto 🎉
