### ISSUE TITLE
onComplete?

### ISSUE THREAD

**Issue by vanderlin** [iamdustan/smoothscroll#57]
Is there a callback when reached target?

**Comment by jeremenichelli** [comment]
Since the primary intention of this repository is to serve as a polyfill adding something that is not contained on the spec is not recommended.

Imagine a case where you use this `onComplete` method, but then a browser starts supporting natively this API and your code does not work or it even breaks.

My suggestion would be to add a throttled event listener before calling an action and removing it after.
