### ISSUE TITLE
Smooth Scroll doesn't work in Firefox 54

### ISSUE THREAD

**Issue by freitasskeeled** [iamdustan/smoothscroll#72]
I'm using this .js in an Angular 4 app. It works well in all the browsers except in Firefox 54. In that version is has no scroll.

`document.getElementById('foo').scrollIntoView({ behavior: 'smooth' });`

This is an example of code that I'm using.

Please suggest any fix or workaround.

Thank you.

[EDIT]

So the issue seems to disappear if we don't have the following instruction in the same "scope" of the previous one:

`window.scroll(0, window.scrollY - 50);`

(we did this to adjust the position after the scroll).

So to be clear: if we have both instructions, there is no scroll at all... if only the first one exists, then we have a smooth scroll.

That being said, I'm not sure if this is a bug related to your polyfill but it's worth checking out I think.

Thank you

**Comment by crccheck** [comment]
Since Firefox supports smooth scrolling, this library doesn't do anything in Firefox. That said, I've noticed that the polyfill is way better than Firefox's implementation and I'd be interested in having a way to always use the polyfill even in Firefox. I tried searching for a relevant Firefox Bugzilla bug but I'm having trouble finding a good search term.

**Comment by jeremenichelli** [comment]
Have you tested this without including the polyfill in your bundle? As @crccheck said, the polyfill does nothing in Firefox since native support is detected.

**Comment by freitasskeeled** [comment]
Yes, the behaviour that I described only happens with the polyfill added to the bundle...

**Comment by jeremenichelli** [comment]
I confirm that in Firefox 54 and 55 the polyfill doesn't do anything. So closing this.
