### ISSUE TITLE
Scroll window to top of specified element?

### ISSUE THREAD

**Issue by jamiewilson** [iamdustan/smoothscroll#85]
The default behavior for an anchor jumps the window to where the top of the element is at the top of the viewport. Is this not possible with smoothscroll?

**Comment by jeremenichelli** [comment]
If I understood well, this would be possible to do doing the following:

```js
document.querySelector('a[#some-anchor]').addEventListener('click', e => {
  e.preventDefault();
  document.querySelector(this.href).scrollIntoView();
});
```

You can also iterate over a collection of anchors with some class or dataset attribute, get the href and assign the listener to each anchor dynamically.

**Comment by jamiewilson** [comment]
Hm. It looks like In Chrome 61, this actually scrolls the element to the center of the window, and scrolls to the middle of the content within it as well. It works as expected in Safari.

**Comment by jeremenichelli** [comment]
Yes, This is because Chrome 61 has already implemented its own version of the spec. I've reported the differences with the Firefox one to see if they can come along so that they match.

If you want the same behavior in all browsers you can force an override adding `window.__forceSmoothScrollPolyfill__ = true` before adding the polyfill, hence it will override Firefox implementation.

**Comment by jamiewilson** [comment]
Ah, got it. Thanks for the help!
