### ISSUE TITLE
Edge Bug

### ISSUE THREAD

**Issue by Moofx** [iamdustan/smoothscroll#90]
I think it dont function as intended in Edge (actualy didnt worked in any IE).
- scroll to left didnt worked at all.
- scroll vertical functional somehow random (when page is in state y = 0 .. so at very top, it didnt move at all)
- but it is possible that it is error with my webpack config:
  I followed this article for adding polyfill:
   http://madole.xyz/using-webpack-to-set-up-polyfills-in-your-site/

**Comment by jeremenichelli** [comment]
I will try to check the polyfill in some IE version to check if some of the last changes broke it. 

Hope to come back soon.

**Comment by jeremenichelli** [comment]
I just tested the polyfill site (iamdustan.com/smoothscroll) in IE11 and all the cases worked perfectly.

I think the problem might be including the polyfills like you are doing from the tutorial. IN this case is better to include the script directly in the bundle of your project since it doesn't covers the extension of the global object but a change in behaviors and overrides.
